# Alpine Linux 3.6
FROM alpine:3.6 

# Ubuntu 16.04
# FROM ubuntu:16.04

# CentOS 6.9
# FROM centos:6.9

# Debian based image with Java 8 jdk
# FROM openjdk:8-jdk

# Debian based image with Python 3.6
# FROM python:3.6

# Debian based image with Python 2.7
# FROM python:2.7